### ISSUE TITLE
Yes/No Buttons

### ISSUE THREAD

**Issue by JamesBerryman** [JamesBerryman/CompletedYet#1]
Yes/No Buttons don't work. 
When Yes selected, should remove item from Array, and continue onto the next item, which would be gamesList[0] (as first item removed.

Then, when No is selected, it should move on to the next item, which would be easy if I could go 1,2,3,4,5. But if Yes has been selected to remove one of those, the order would be changed when selected No.

**Comment by KroFunk** [comment]
Check [KroBranch](https://github.com/JamesBerryman/CompletedYet/tree/KroBranch). I have made a pull request so you can merge it into your code if you wish.

**Comment by JamesBerryman** [comment]
Thank you Krofunk for fixing this issue!
